-- Estado antes da V11: coluna legada endereco_os (a V11 renomeia para endereco_linha1_os e acrescenta outros campos).
-- Sem esta tabela, ambientes só com Flyway falham no ALTER da V11.
CREATE TABLE IF NOT EXISTS parametros_empresa (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    nome_empresa VARCHAR(255) NULL,
    logo_url TEXT NULL,
    mensagem_boas_vindas VARCHAR(255) NULL,
    cor_primaria VARCHAR(32) NULL DEFAULT '#2563eb',
    cor_secundaria VARCHAR(32) NULL DEFAULT '#1e3a8a',
    cor_fundo VARCHAR(32) NULL DEFAULT '#f9fafb',
    cor_texto VARCHAR(32) NULL DEFAULT '#111827',
    cor_botao VARCHAR(32) NULL DEFAULT '#2563eb',
    cor_botao_texto VARCHAR(32) NULL DEFAULT '#ffffff',
    chave_pix VARCHAR(255) NULL,
    suporte_email VARCHAR(255) NULL,
    suporte_whatsapp VARCHAR(255) NULL,
    segmento VARCHAR(20) NOT NULL DEFAULT 'GERAL',
    modulo_farmacia_ativo TINYINT(1) NOT NULL DEFAULT 0,
    farmacia_lote_validade_obrigatorio TINYINT(1) NOT NULL DEFAULT 0,
    farmacia_controlados_ativo TINYINT(1) NOT NULL DEFAULT 0,
    farmacia_antimicrobianos_ativo TINYINT(1) NOT NULL DEFAULT 0,
    farmacia_pmc_ativo TINYINT(1) NOT NULL DEFAULT 0,
    farmacia_pmc_modo VARCHAR(20) NOT NULL DEFAULT 'ALERTA',
    modulo_informatica_ativo TINYINT(1) NOT NULL DEFAULT 0,
    cnpj VARCHAR(255) NULL,
    telefone_comercial VARCHAR(255) NULL,
    email_comercial VARCHAR(255) NULL,
    endereco_os TEXT NULL,
    texto_termos_os TEXT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    UNIQUE KEY uk_parametros_empresa_company (company_id),
    CONSTRAINT fk_parametros_empresa_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
