-- Ordem de serviço (módulo informática); antes só existia via Hibernate em alguns ambientes.
CREATE TABLE IF NOT EXISTS ordens_servico (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    numero_os BIGINT NOT NULL,
    cliente_id BIGINT NULL,
    nome_cliente VARCHAR(255) NOT NULL,
    telefone_cliente VARCHAR(255) NULL,
    contato_cliente VARCHAR(255) NULL,
    equipamento VARCHAR(255) NULL,
    marca VARCHAR(255) NULL,
    modelo VARCHAR(255) NULL,
    numero_serie VARCHAR(255) NULL,
    acessorios VARCHAR(255) NULL,
    defeito_relatado TEXT NULL,
    diagnostico TEXT NULL,
    servico_executado TEXT NULL,
    tecnico_responsavel VARCHAR(255) NULL,
    observacao TEXT NULL,
    valor_servico DECIMAL(10, 2) NOT NULL DEFAULT 0,
    desconto DECIMAL(10, 2) NOT NULL DEFAULT 0,
    valor_total DECIMAL(10, 2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'ABERTA',
    data_abertura DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    data_previsao_entrega DATE NULL,
    data_conclusao DATETIME(6) NULL,
    data_entrega DATETIME(6) NULL,
    venda_id BIGINT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NULL,
    INDEX idx_ordens_servico_company (company_id),
    CONSTRAINT fk_ordens_servico_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_ordens_servico_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);
